upstream storefront_app {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    # Certbot renewal path
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name _;

    # SSL Certificates (managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/mystore67.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mystore67.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 20M;

    # Static Files
    location /static/ {
        alias /app/static/;
    }

    # Media Files
    location /media/ {
        alias /app/media/;
    }

    # API and Admin requests
    location / {
        proxy_pass http://storefront_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }
}
